[profile.default]
remappings = ["openzeppelin-contracts/=./lib/openzeppelin-contracts/contracts/"]
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./requests" },
    { access = "read", path = "./models" },
    { access = "read-write", path = "./completionIds" },
    { access = "read-write", path = "./results" },
]

[fmt]
line_length = 120
ignore = ["lib"]
