[profile.default]
remappings = ["openzeppelin-contracts/=./lib/openzeppelin-contracts/contracts/"]
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fmt]
line_length = 120
ignore = ["lib"]
